version: '3.3'

services:
  app:
    image: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
