version: '3.3'

services:
  app:
    image: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: springboot-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    networks:
      - network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  network:
