version: '3.3'

services:
  app-service:
    image: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: springboot-app-container
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_HOST: db-service
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    networks:
      - network
    depends_on:
      - db-service

  db-service:
    image: mysql:8.0
    container_name: mysql-container
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    networks:
      - network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  network:
